<Project>
    <PropertyGroup>
        <Version Condition="'$(Version)' == ''">0.7.0</Version>
        <Company>Excel on the Web</Company>
        <Product>TypeWhisper</Product>
        <Copyright>Copyright © 2026 Excel on the Web. Portions © 2026 TypeWhisper.</Copyright>
    </PropertyGroup>
</Project>
